pipeline{
    agent{node{label 'maven'}}
    options{skipDefaultCheckout true}
    stages{
        stage('Checkout'){
            steps{
                sendNotifications('started','team@example.com')
                git branch: 'notifications',
                url: 'https://github.com/xdelios/DO400-apps.git'
            }
        }

        stage('Test'){
            steps{
                dir('simple-calculator'){
                    sh './mvnw clean test'
                }
            }
        }
    }
    post{
        always {
            sendNotifications('finished', 'team@example.com')
        }
    }
}

void sendNotifications(String action, String email){
    mail to: "${email}",
    subject: "Pipeline ${action}: ${currentBuild.fullDisplayName}",
    body: "The following pipeline ${action}: ${env.BUILD_URL}"
}