pipeline{
    agent{node{label 'maven'}}
    options{skipDefaultCheckout true}
    stages{
        stage('Checkout'){
            steps{
                git branch: 'notifications',
                url: 'https://github.com/xdelios/DO400-apps.git'
            }
        }

        stage('Test'){
            steps{
                dir('simple-calculator'){
                    sh './mvnw clean test'
                }
            }
        }
    }
}