pipeline{
    agent any
    stages{
        stage("Deploy"){
            steps{
                sh """
                    oc project rplvvx-deploy-strategies
                    oc start-build greeting-service --follow --wait
                """
            }
        }
    }
}
