pipeline{
    agent any
        stage("Deploy"){
            steps{
                sh """
                    oc project rplvvx-deployment-strategies
                    oc start-build greeting-service --follow --wait
                """
            }
        }
}
